language: php

env:
 # - MAGENTO_VERSION="1.5.0.1"
#  - MAGENTO_VERSION="1.6.0.0"
#  - MAGENTO_VERSION="1.6.1.0"
  - MAGENTO_VERSION="1.6.2.0"
#  - MAGENTO_VERSION="1.7.0.0"
#  - MAGENTO_VERSION="1.7.0.1"
  - MAGENTO_VERSION="1.7.0.2"
#  - MAGENTO_VERSION="1.8.0.0"
  - MAGENTO_VERSION="1.8.1.0"
#  - MAGENTO_VERSION="1.9.0.0"
  - MAGENTO_VERSION="1.9.0.1"
  - MAGENTO_VERSION="1.9.1.0"

php:
  - 5.3
  - 5.4
  - 5.5

before_install:

before_script:
  - CURR_DIR=$(pwd)

  #move locator extension to new folder
  #- mkdir $CURR_DIR/locator
  - rsync -a $CURR_DIR/ $CURR_DIR/locator --exclude $CURR_DIR/locator --exclude $CURR_DIR/mageci --exclude $CURR_DIR/phpunit --exclude $CURR_DIR/magento

  #install mage ci
  - git clone git://github.com/EcomDev/MageCI.git $CURR_DIR/mageci/

  #install modman
  - wget https://raw.githubusercontent.com/colinmollenhour/modman/master/modman -O $CURR_DIR/mageci/bin/modman
  - chmod +x $CURR_DIR/mageci/bin/modman

  #install magento
  - $CURR_DIR/mageci/bin/mage-ci install magento $MAGENTO_VERSION magento_test -c -t -r http://mage-ci.ecomdev.org

  #install php unit
  - git clone git://github.com/EcomDev/EcomDev_PHPUnit.git -b dev $CURR_DIR/phpunit/
  - $CURR_DIR/mageci/bin/mage-ci install-module magento $CURR_DIR/phpunit

  #install locator to magento directory
  - $CURR_DIR/mageci/bin/mage-ci install-module magento $CURR_DIR/locator

  - cp ./.travis/composer.json magento
  - cd magento
  - composer install --prefer-dist
script:

  - wget https://scrutinizer-ci.com/ocular.phar
  - phpunit --coverage-clover=coverage.clover
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
